Adiciona hook para não permitir commit na master

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -8,3 +8,11 @@ git diff --cached --name-only | \
 grep -E $FILES_PATTERN | \
 xargs grep --with-filename -n $FORBIDDEN | \
 grep -v '//' && echo 'COMMIT REJECTED!  Found console.log references. Please remove them before committing.' && exit 1
+
+# Check to see if we are on master branch. Stop accidental commits
+if [ $(git symbolic-ref HEAD 2>/dev/null) == "refs/heads/master" ]
+then
+  echo "Cannot commit to master branch"
+  exit 1
+fi
+exit 0
